spring:
  application:
    name: siebel-s-tools
  profiles:
    active: remote

#默认端口
server:
  port: 8082

---
spring:
  profiles: remote
  #数据库配置
  datasource:
    druid:
      source:  #数据源1
        driverClassName: oracle.jdbc.OracleDriver
        jdbc-url: ***
        username: **
        password: *!#**
      dest:  #数据源2
        driverClassName: oracle.jdbc.OracleDriver
        jdbc-url: ***
        username: ***
        password: **



#端口
server:
  port: 8082

logging:
  level:
    com.example.diff.source.dao.mapper: DEBUG
    com.example.diff.dest.dao.mapper: DEBUG

project:
  build:
    sourceEncoding: UTF-8

#mybatis config
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  config-location: classpath:mybatis-config.xml