spring:
  application:
    name: lnkcrm-business
  profiles:
    active: remote

#默认端口
server:
  port: 8082

---
spring:
  profiles: remote
  #数据库配置
  datasource:
    driverClassName: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@172.31.100.51:1521:CRMPROD
    url1: jdbc:oracle:thin:@172.31.100.51:1521:CRMPROD
    url2: jdbc:oracle:thin:@172.31.100.51:1521:CRMPROD
    username: SADMIN
    password: Sadm123!#
    max-active: 10000
    max-idle: 20
    min-idle: 2
    max-wait: 600000
    test-on-borrow: true
    test-while-idle: true
    validation-query: select 1 from dual
    initial-size: 10
    username2: SADMIN
    password2: Sadm123!#

#端口
server:
  port: 8082

logging:
  level:
    com.example.diff.dao.mapper: DEBUG

project:
  build:
    sourceEncoding: UTF-8

#mybatis config
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml