#东鹏DMS测试环境配置文件
spring:
  profiles: dpuat
  #数据库配置
  datasource:
    driverClassName: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@172.18.10.20:1521:LINKCRM
    url1: jdbc:oracle:thin:@172.18.10.20:1521:LINKCRM
    url2: jdbc:oracle:thin:@172.18.10.20:1521:LINKCRM
    username: linkcrm_stage
    password: Dpcrm2017
    max-active: 10000
    max-idle: 20
    min-idle: 2
    max-wait: 600000
    test-on-borrow: true
    test-while-idle: true
    validation-query: select 1 from dual
    initial-size: 10
    username2: SIEBEL
    password2: Sebluat01
  activemq:
      broker-url: tcp://172.18.10.21:61616
      user: admin
      password: admindp2017
  jms:
      pub-sub-domain: false
  http:
    encoding:
      charset: UTF-8 
      enabled: true
      force: true
  application:
    name: diff
    
#端口
server:
  port: 8082


project:
  build:
    sourceEncoding: UTF-8

#log4j config
logging:
  config: classpath:log4j2-debug.xml

#mybatis config
mybatis:
  typeAliasesPackage: com.hand.**.model,com.dongpeng.**.model
  mapperLocations: classpath*:com/hand/**/sqlMap/*Mapper.xml,classpath*:com/dongpeng/**/sqlMap/*Mapper.xml
  config-location: mybatis-config.xml

spring
  mvc
    view
      prefix=/page/

spring
  mvc
    view
      suffix=.html